/* Source and licensing information for the line(s) below can be found at https://www.nestle.com/libraries/blazy/blazy.js. */
(function(root,blazy){if(typeof define==='function'&&define.amd){define(blazy)}else if(typeof exports==='object'){module.exports=blazy()}else root.Blazy=blazy()})(this,function(){'use strict';var _source,_viewport,_isRetina,_supportClosest,_attrSrc='src',_attrSrcset='srcset';return function Blazy(options){if(!document.querySelectorAll){var s=document.createStyleSheet();document.querySelectorAll=function(r,c,i,j,a){a=document.all,c=[],r=r.replace(/\[for\b/gi,'[htmlFor').split(',');for(i=r.length;i--;){s.addRule(r[i],'k:v');for(j=a.length;j--;)a[j].currentStyle.k&&c.push(a[j]);s.removeRule(0)};return c}};var scope=this,util=scope._util={};util.elements=[];util.destroyed=true;scope.options=options||{};scope.options.error=scope.options.error||false;scope.options.offset=scope.options.offset||100;scope.options.root=scope.options.root||document;scope.options.success=scope.options.success||false;scope.options.selector=scope.options.selector||'.b-lazy';scope.options.separator=scope.options.separator||'|';scope.options.containerClass=scope.options.container;scope.options.container=scope.options.containerClass?document.querySelectorAll(scope.options.containerClass):false;scope.options.errorClass=scope.options.errorClass||'b-error';scope.options.breakpoints=scope.options.breakpoints||false;scope.options.loadInvisible=scope.options.loadInvisible||false;scope.options.successClass=scope.options.successClass||'b-loaded';scope.options.validateDelay=scope.options.validateDelay||25;scope.options.saveViewportOffsetDelay=scope.options.saveViewportOffsetDelay||50;scope.options.srcset=scope.options.srcset||'data-srcset';scope.options.src=_source=scope.options.src||'data-src';_supportClosest=Element.prototype.closest;_isRetina=window.devicePixelRatio>1;_viewport={};_viewport.top=0-scope.options.offset;_viewport.left=0-scope.options.offset;scope.revalidate=function(){initialize(scope)};scope.load=function(elements,force){var opt=this.options;if(elements&&elements.length===undefined){loadElement(elements,force,opt)}else each(elements,function(element){loadElement(element,force,opt)})};scope.destroy=function(){var util=scope._util;if(scope.options.container)each(scope.options.container,function(object){unbindEvent(object,'scroll',util.validateT)});unbindEvent(window,'scroll',util.validateT);unbindEvent(window,'resize',util.validateT);unbindEvent(window,'resize',util.saveViewportOffsetT);util.count=0;util.elements.length=0;util.destroyed=true};util.validateT=throttle(function(){validate(scope)},scope.options.validateDelay,scope);util.saveViewportOffsetT=throttle(function(){saveViewportOffset(scope.options.offset)},scope.options.saveViewportOffsetDelay,scope);saveViewportOffset(scope.options.offset);each(scope.options.breakpoints,function(object){if(object.width>=window.screen.width){_source=object.src;return false}});setTimeout(function(){initialize(scope)})}
function initialize(self){var util=self._util;util.elements=toArray(self.options);util.count=util.elements.length;if(util.destroyed){util.destroyed=false;if(self.options.container)each(self.options.container,function(object){bindEvent(object,'scroll',util.validateT)});bindEvent(window,'resize',util.saveViewportOffsetT);bindEvent(window,'resize',util.validateT);bindEvent(window,'scroll',util.validateT)};validate(self)}
function validate(self){var util=self._util;for(var i=0;i<util.count;i++){var element=util.elements[i];if(elementInView(element,self.options)||hasClass(element,self.options.successClass)){self.load(element);util.elements.splice(i,1);util.count--;i--}};if(util.count===0)self.destroy()}
function elementInView(ele,options){var rect=ele.getBoundingClientRect();if(options.container&&_supportClosest){var elementContainer=ele.closest(options.containerClass);if(elementContainer){var containerRect=elementContainer.getBoundingClientRect();if(inView(containerRect,_viewport)){var top=containerRect.top-options.offset,right=containerRect.right+options.offset,bottom=containerRect.bottom+options.offset,left=containerRect.left-options.offset,containerRectWithOffset={top:top>_viewport.top?top:_viewport.top,right:right<_viewport.right?right:_viewport.right,bottom:bottom<_viewport.bottom?bottom:_viewport.bottom,left:left>_viewport.left?left:_viewport.left};return inView(rect,containerRectWithOffset)}else return false}};return inView(rect,_viewport)}
function inView(rect,viewport){return rect.right>=viewport.left&&rect.bottom>=viewport.top&&rect.left<=viewport.right&&rect.top<=viewport.bottom}
function loadElement(ele,force,options){if(!hasClass(ele,options.successClass)&&(force||options.loadInvisible||(ele.offsetWidth>0&&ele.offsetHeight>0))){var dataSrc=getAttr(ele,_source)||getAttr(ele,options.src);if(dataSrc){var dataSrcSplitted=dataSrc.split(options.separator),src=dataSrcSplitted[_isRetina&&dataSrcSplitted.length>1?1:0],srcset=getAttr(ele,options.srcset),isImage=equal(ele,'img'),parent=ele.parentNode,isPicture=parent&&equal(parent,'picture');if(isImage||ele.src===undefined){var img=new Image(),onErrorHandler=function(){if(options.error)options.error(ele,"invalid");addClass(ele,options.errorClass);unbindEvent(img,'error',onErrorHandler);unbindEvent(img,'load',onLoadHandler)},onLoadHandler=function(){if(isImage){if(!isPicture)handleSources(ele,src,srcset)}else ele.style.backgroundImage='url("'+src+'")';itemLoaded(ele,options);unbindEvent(img,'load',onLoadHandler);unbindEvent(img,'error',onErrorHandler)};if(isPicture){img=ele;each(parent.getElementsByTagName('source'),function(source){handleSource(source,_attrSrcset,options.srcset)})};bindEvent(img,'error',onErrorHandler);bindEvent(img,'load',onLoadHandler);handleSources(img,src,srcset)}else{ele.src=src;itemLoaded(ele,options)}}else if(equal(ele,'video')){each(ele.getElementsByTagName('source'),function(source){handleSource(source,_attrSrc,options.src)});ele.load();itemLoaded(ele,options)}else{if(options.error)options.error(ele,"missing");addClass(ele,options.errorClass)}}}
function itemLoaded(ele,options){addClass(ele,options.successClass);if(options.success)options.success(ele);removeAttr(ele,options.src);removeAttr(ele,options.srcset);each(options.breakpoints,function(object){removeAttr(ele,object.src)})}
function handleSource(ele,attr,dataAttr){var dataSrc=getAttr(ele,dataAttr);if(dataSrc){setAttr(ele,attr,dataSrc);removeAttr(ele,dataAttr)}}
function handleSources(ele,src,srcset){if(srcset)setAttr(ele,_attrSrcset,srcset);ele.src=src}
function setAttr(ele,attr,value){ele.setAttribute(attr,value)}
function getAttr(ele,attr){return ele.getAttribute(attr)}
function removeAttr(ele,attr){ele.removeAttribute(attr)}
function equal(ele,str){return ele.nodeName.toLowerCase()===str}
function hasClass(ele,className){return(' '+ele.className+' ').indexOf(' '+className+' ')!==-1}
function addClass(ele,className){if(!hasClass(ele,className))ele.className+=' '+className}
function toArray(options){var array=[],nodelist=(options.root).querySelectorAll(options.selector);for(var i=nodelist.length;i--;array.unshift(nodelist[i]));return array}
function saveViewportOffset(offset){_viewport.bottom=(window.innerHeight||document.documentElement.clientHeight)+offset;_viewport.right=(window.innerWidth||document.documentElement.clientWidth)+offset}
function bindEvent(ele,type,fn){if(ele.attachEvent){ele.attachEvent&&ele.attachEvent('on'+type,fn)}else ele.addEventListener(type,fn,{capture:false,passive:true})}
function unbindEvent(ele,type,fn){if(ele.detachEvent){ele.detachEvent&&ele.detachEvent('on'+type,fn)}else ele.removeEventListener(type,fn,{capture:false,passive:true})}
function each(object,fn){if(object&&fn){var l=object.length;for(var i=0;i<l&&fn(object[i],i)!==false;i++);}}
function throttle(fn,minDelay,scope){var lastCall=0;return function(){var now=+new Date();if(now-lastCall<minDelay)return;lastCall=now;fn.apply(scope,arguments)}}})
/* Source and licensing information for the above line(s) can be found at https://www.nestle.com/libraries/blazy/blazy.js. */;
